### ISSUE TITLE
Internal Server Error on PUT: non-fatal PostgreSQL error message: No hstore extension installed.

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/twintip-storage#1] opened 2015-09-17 10:31 UTC
```
 ERROR [qtp1473829090-38] [PUT /apps/myapp <- 52.16.1.2] i.s.s.parser - internal server error com.netflix.hystrix.exception.HystrixBadRequestException: non-fatal postgresql message
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: com.netflix.hystrix.exception.HystrixBadRequestException: non-fatal postgresql message
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at org.zalando.stups.twintip.storage.sql$fn__9635$cmd_create_or_update_api_BANG___9636.doInvoke(sql.clj:29) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at clojure.core$apply.invoke(core.clj:630) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at com.netflix.hystrix.core$fn__8006$fn__8008.invoke(core.clj:714) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at com.netflix.hystrix.core.proxy$com.netflix.hystrix.HystrixCommand$ff19274a.run(Unknown Source) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at rx.Observable$1.call(Observable.java:145) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at rx.Observable$1.call(Observable.java:137) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at rx.Observable$1.call(Observable.java:145) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at rx.Observable$1.call(Observable.java:137) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at rx.Observable$1.call(Observable.java:145) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at rx.Observable$1.call(Observable.java:137) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at rx.Observable.unsafeSubscribe(Observable.java:7713) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:534) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:509) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at rx.Observable.unsafeSubscribe(Observable.java:7713) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[twintip-storage.jar:?]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_45-internal]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_45-internal]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_45-internal]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_45-internal]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: #011at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
 Sep 17 10:28:47 ip-172-31-157-120 docker/ff9943e188c5[816]: Caused by: org.postgresql.util.PSQLException: No hstore extension installed.

**Comment by fmueller** [comment] 2016-06-07 08:19
Not reproducible since then. That's why I close this issue.

**Closed by fmueller** 2016-06-07 08:19 UTC
Labels: bug
